<?php
require_once __DIR__ . '/auth.php';
require_once __DIR__ . '/../conexion.php';
$notice = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $id = (int)($_POST['id'] ?? 0); $role = $_POST['rol'] ?? '';
    if ($id === (int)$_SESSION['usuario_id']) $notice = 'No puedes cambiar el rol de tu propia cuenta.';
    elseif (!in_array($role, ['admin', 'cliente'], true)) $notice = 'El rol seleccionado no es válido.';
    else {
        $find = $conexion->prepare('SELECT rol FROM usuarios WHERE id=?'); $find->execute([$id]); $target = $find->fetch();
        if (!$target) $notice = 'No encontramos esa cuenta.';
        elseif ($target['rol'] === 'admin' && $role !== 'admin' && (int)$conexion->query("SELECT COUNT(*) FROM usuarios WHERE rol='admin'")->fetchColumn() <= 1) $notice = 'Debe quedar al menos una cuenta administradora.';
        else { $update = $conexion->prepare('UPDATE usuarios SET rol=? WHERE id=?'); $update->execute([$role, $id]); header('Location: usuarios.php?guardado=1'); exit; }
    }
}
$allUsers = $conexion->query('SELECT id,nombre_completo,correo_electronico,rol,foto_perfil FROM usuarios ORDER BY id DESC')->fetchAll();
$query = trim($_GET['q'] ?? ''); $roleFilter = $_GET['rol'] ?? '';
$users = array_values(array_filter($allUsers, static function ($user) use ($query, $roleFilter) {
    $matches = $query === '' || stripos($user['nombre_completo'], $query) !== false || stripos($user['correo_electronico'], $query) !== false;
    return $matches && ($roleFilter === '' || $user['rol'] === $roleFilter);
}));
$adminCount = count(array_filter($allUsers, static fn($user) => $user['rol'] === 'admin'));
$avatar = !empty($_SESSION['foto_perfil']) ? '../' . $_SESSION['foto_perfil'] : 'https://ui-avatars.com/api/?name=' . rawurlencode($_SESSION['usuario_nombre'] ?? 'Admin') . '&background=0876ea&color=fff';
function h($value) { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Usuarios | Sport Max Admin</title><link rel="stylesheet" href="admin.css"></head><body class="admin-body">
<aside class="admin-sidebar"><a class="admin-brand" href="../index.php">SPORT<span>MAX</span></a><p class="admin-label">Administración</p><nav class="admin-nav"><a href="dashboard.php"><span class="ico">◈</span>Resumen</a><a href="productos.php"><span class="ico">▣</span>Productos</a><a class="active" href="usuarios.php"><span class="ico">♙</span>Usuarios</a><a href="mensajes.php"><span class="ico">✉</span>Mensajes</a><a href="../perfil.php"><span class="ico">◉</span>Mi perfil</a></nav><div class="sidebar-account"><img src="<?= h($avatar) ?>" alt=""><div><strong><?= h($_SESSION['usuario_nombre'] ?? 'Admin') ?></strong><small>Administrador</small></div><a href="../logout.php">↗</a></div></aside>
<main class="admin-main"><header class="admin-topbar"><span class="crumb">Sport Max / Comunidad</span><div class="top-links"><a href="../index.php">↗ Ver tienda</a><a href="../logout.php">Cerrar sesión</a></div></header><section class="admin-hero"><span class="kicker">Comunidad Sport Max</span><h1>Personas detrás del movimiento</h1><p>Consulta las cuentas registradas y cuida quién administra tu tienda.</p></section>
<?php if ($notice): ?><div class="error-note" role="alert"><?= h($notice) ?></div><?php elseif (isset($_GET['guardado'])): ?><div class="success-note">El rol de la cuenta se actualizó.</div><?php endif; ?>
<section class="stats-row"><article class="mini-stat"><span class="stat-ico">♙</span><div><small>Cuentas totales</small><strong><?= count($allUsers) ?></strong></div></article><article class="mini-stat"><span class="stat-ico">★</span><div><small>Administradores</small><strong><?= $adminCount ?></strong></div></article><article class="mini-stat"><span class="stat-ico">◉</span><div><small>Clientes</small><strong><?= count($allUsers) - $adminCount ?></strong></div></article><article class="mini-stat"><span class="stat-ico">⌕</span><div><small>Resultados</small><strong><?= count($users) ?></strong></div></article></section>
<div class="heading-row"><div><h2>Directorio de usuarios</h2><p>Los cambios de rol se aplican inmediatamente.</p></div></div><section class="admin-card"><div class="toolbar"><form class="search-form" method="get"><input type="search" name="q" value="<?= h($query) ?>" placeholder="Buscar por nombre o correo"><select name="rol"><option value="">Todos los roles</option><option value="cliente" <?= $roleFilter === 'cliente' ? 'selected' : '' ?>>Clientes</option><option value="admin" <?= $roleFilter === 'admin' ? 'selected' : '' ?>>Administradores</option></select><button class="admin-button-secondary">Filtrar</button></form></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Cuenta</th><th>Correo electrónico</th><th>Rol</th><th>Administrar acceso</th></tr></thead><tbody><?php foreach ($users as $user): $userAvatar = !empty($user['foto_perfil']) ? '../' . $user['foto_perfil'] : 'https://ui-avatars.com/api/?name=' . rawurlencode($user['nombre_completo']) . '&background=eaf3ff&color=0876ea'; ?><tr><td><div class="item-cell"><img class="avatar-small" src="<?= h($userAvatar) ?>" alt=""><span><?= h($user['nombre_completo']) ?></span></div></td><td><?= h($user['correo_electronico']) ?></td><td><span class="badge <?= $user['rol'] === 'admin' ? 'role-admin' : 'role-client' ?>"><?= $user['rol'] === 'admin' ? 'Administrador' : 'Cliente' ?></span></td><td><?php if ((int)$user['id'] === (int)$_SESSION['usuario_id']): ?><span class="muted">Tu sesión actual</span><?php else: ?><form method="post" class="form-actions"><input type="hidden" name="id" value="<?= (int)$user['id'] ?>"><select class="field" name="rol" aria-label="Rol de <?= h($user['nombre_completo']) ?>" style="max-width:145px"><option value="cliente" <?= $user['rol'] === 'cliente' ? 'selected' : '' ?>>Cliente</option><option value="admin" <?= $user['rol'] === 'admin' ? 'selected' : '' ?>>Administrador</option></select><button class="admin-button-secondary">Guardar</button></form><?php endif; ?></td></tr><?php endforeach; ?><?php if (!$users): ?><tr><td colspan="4"><div class="admin-empty">No encontramos cuentas con esos filtros.</div></td></tr><?php endif; ?></tbody></table></div></section><footer class="admin-footer">SPORT MAX · Administración de usuarios</footer></main></body></html>
