<?php
require_once __DIR__ . '/auth.php';
require_once __DIR__ . '/../conexion.php';
if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'delete') {
    $delete = $conexion->prepare('DELETE FROM contacto WHERE id=?'); $delete->execute([(int)($_POST['id'] ?? 0)]);
    header('Location: mensajes.php?eliminado=1'); exit;
}
$error = '';
try { $allMessages = $conexion->query('SELECT * FROM contacto ORDER BY id DESC')->fetchAll(); }
catch (Throwable $e) { $allMessages = []; $error = 'No encontramos la tabla de mensajes. Revisa el esquema de contacto.'; }
$query = trim($_GET['q'] ?? ''); $kind = $_GET['tipo'] ?? '';
$messages = array_values(array_filter($allMessages, static function ($message) use ($query, $kind) {
    $text = ($message['nombre'] ?? '') . ' ' . ($message['email'] ?? '') . ' ' . ($message['mensaje'] ?? '');
    return ($query === '' || stripos($text, $query) !== false) && ($kind === '' || ($message['tipo_mensaje'] ?? '') === $kind);
}));
$kinds = array_values(array_unique(array_filter(array_column($allMessages, 'tipo_mensaje'))));
$avatar = !empty($_SESSION['foto_perfil']) ? '../' . $_SESSION['foto_perfil'] : 'https://ui-avatars.com/api/?name=' . rawurlencode($_SESSION['usuario_nombre'] ?? 'Admin') . '&background=0876ea&color=fff';
function h($value) { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
function initialOf($value) { return preg_match('/^./us', (string)$value, $match) ? strtoupper($match[0]) : '?'; }
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mensajes | Sport Max Admin</title><link rel="stylesheet" href="admin.css"></head><body class="admin-body">
<aside class="admin-sidebar"><a class="admin-brand" href="../index.php">SPORT<span>MAX</span></a><p class="admin-label">Administración</p><nav class="admin-nav"><a href="dashboard.php"><span class="ico">◈</span>Resumen</a><a href="productos.php"><span class="ico">▣</span>Productos</a><a href="usuarios.php"><span class="ico">♙</span>Usuarios</a><a class="active" href="mensajes.php"><span class="ico">✉</span>Mensajes</a><a href="../perfil.php"><span class="ico">◉</span>Mi perfil</a></nav><div class="sidebar-account"><img src="<?= h($avatar) ?>" alt=""><div><strong><?= h($_SESSION['usuario_nombre'] ?? 'Admin') ?></strong><small>Administrador</small></div><a href="../logout.php">↗</a></div></aside>
<main class="admin-main"><header class="admin-topbar"><span class="crumb">Sport Max / Atención al cliente</span><div class="top-links"><a href="../index.php">↗ Ver tienda</a><a href="../logout.php">Cerrar sesión</a></div></header><section class="admin-hero"><span class="kicker">Cerca de nuestros clientes</span><h1>Escuchamos cada mensaje</h1><p>Solicitudes, ideas y comentarios que ayudan a Sport Max a seguir avanzando.</p></section>
<?php if ($error): ?><div class="error-note" role="alert"><?= h($error) ?></div><?php elseif (isset($_GET['eliminado'])): ?><div class="success-note">El mensaje se eliminó de la bandeja.</div><?php endif; ?>
<section class="stats-row"><article class="mini-stat"><span class="stat-ico">✉</span><div><small>Mensajes recibidos</small><strong><?= count($allMessages) ?></strong></div></article><article class="mini-stat"><span class="stat-ico">⌕</span><div><small>Coincidencias</small><strong><?= count($messages) ?></strong></div></article><article class="mini-stat"><span class="stat-ico">◉</span><div><small>Tipos de mensaje</small><strong><?= count($kinds) ?></strong></div></article><article class="mini-stat"><span class="stat-ico">↗</span><div><small>Respuesta directa</small><strong>Email</strong></div></article></section>
<div class="heading-row"><div><h2>Bandeja de entrada</h2><p>Selecciona responder para abrir tu aplicación de correo.</p></div></div><section class="admin-card"><div class="toolbar"><form class="search-form" method="get"><input type="search" name="q" value="<?= h($query) ?>" placeholder="Buscar nombre, correo o mensaje"><select name="tipo"><option value="">Todos los tipos</option><?php foreach ($kinds as $messageKind): ?><option value="<?= h($messageKind) ?>" <?= $kind === $messageKind ? 'selected' : '' ?>><?= h($messageKind) ?></option><?php endforeach; ?></select><button class="admin-button-secondary">Filtrar</button></form></div><?php if (!$messages): ?><div class="admin-empty"><strong><?= $allMessages ? 'No hay coincidencias' : 'Tu bandeja está despejada' ?></strong><?= $allMessages ? 'Prueba otros términos de búsqueda.' : 'Los mensajes enviados desde la tienda aparecerán aquí.' ?></div><?php else: ?><div class="message-grid"><?php foreach ($messages as $message): ?><article class="admin-card message-card"><div class="message-top"><div class="message-person"><span class="message-avatar"><?= h(mb_strtoupper(mb_substr($message['nombre'] ?? '?', 0, 1, 'UTF-8'), 'UTF-8')) ?></span><div><strong><?= h($message['nombre']) ?></strong><small><?= h($message['email']) ?></small></div></div><span class="message-kind"><?= h($message['tipo_mensaje'] ?? 'General') ?></span></div><p class="message-body"><?= h($message['mensaje']) ?></p><footer class="message-foot"><a class="admin-button-secondary" href="mailto:<?= h($message['email']) ?>?subject=Sport%20Max%20-%20respuesta%20a%20tu%20mensaje">↗ Responder</a><form method="post" onsubmit="return confirm('¿Eliminar este mensaje?')"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= (int)$message['id'] ?>"><button class="admin-button-danger">Eliminar</button></form></footer></article><?php endforeach; ?></div><?php endif; ?></section><footer class="admin-footer">SPORT MAX · Atención al cliente</footer></main></body></html>
